config/routes.rb
Rails.application.routes.draw do

  resources :roasts

end

app/models/roast.rb
class Roast < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController

	def index
		@roasts = Roast.all
	end

	def new
		@roast = Roast.new
	end

	def create
		@roast = Roast.create(roast_params)
		redirect_to '/roasts'
	end

	def roast_params
		params.require(:roast).permit(:name)
	end

	def show
		@roast = Roast.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RailsRoast
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/roasts/index.html.haml
.row
	.three.columns
		%a{:href => '/roasts/new', :class => 'button', :id => 'add'} Add a roast
%br
.row
	- if @roasts.any?
		- @roasts.all.each do |roast|
			.row
				.three.columns
					%li= link_to roast.name, roast_path(roast)
	- else
		%h1 No roasts yet!

app/views/roasts/new.html.haml
.row
	.three.columns
		= form_for @roast do |f|
			= f.label :name
			= f.text_field :name
			%input{:type => 'submit', :value => 'Add Roast', :class => 'button'}

.row
	.three.columns
		%a{:href => '/roasts', :class => 'button'} All Roasts

app/views/roasts/show.html.haml
.row
	.three.columns
		%h4= @roast.name
		%p= @roast.description